// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type AchievementDef struct {
	Id          int64  `json:"id"`
	Key         string `json:"key"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
	Category    string `json:"category"`
	Threshold   int    `json:"threshold"`
	Progress    int    `json:"progress"`
	Unlocked    bool   `json:"unlocked"`
	UnlockedAt  string `json:"unlocked_at,omitempty"`
}

type AchievementItem struct {
	Type  string `json:"type"`
	Count int    `json:"count"`
}

type AdminChangePasswordReq struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type AdminDashboardStatsResp struct {
	Code           int    `json:"code"`
	Success        bool   `json:"success"`
	Message        string `json:"message"`
	TotalUsers     int64  `json:"total_users"`
	TodayNewUsers  int64  `json:"today_new_users"`
	TotalMatches   int64  `json:"total_matches"`
	OngoingMatches int64  `json:"ongoing_matches"`
}

type AdminEventNewsCreateReq struct {
	Title          string `json:"title"`
	Summary        string `json:"summary,optional"`
	Content        string `json:"content,optional"`
	CoverImage     string `json:"cover_image,optional"`
	SourceType     string `json:"source_type,optional"`
	SourceName     string `json:"source_name,optional"`
	SourceUrl      string `json:"source_url,optional"`
	Published      bool   `json:"published,optional"`
	SortTime       string `json:"sort_time,optional"`
	TournamentId   int64  `json:"tournament_id,optional"`
	TournamentName string `json:"tournament_name"`
	GameType       int    `json:"game_type"`
	Description    string `json:"description,optional"`
	Country        string `json:"country,optional"`
	City           string `json:"city,optional"`
	Venue          string `json:"venue,optional"`
	StartDate      string `json:"start_date"`
	EndDate        string `json:"end_date,optional"`
	StartTime      string `json:"start_time,optional"`
	EndTime        string `json:"end_time,optional"`
	Status         int    `json:"status"`
}

type AdminEventNewsIdReq struct {
	EventId int64 `json:"event_id"`
}

type AdminEventNewsListReq struct {
	Page      int `form:"page,default=1"`
	PageSize  int `form:"page_size,default=20"`
	Status    int `form:"status,optional,default=-1"`
	GameType  int `form:"game_type,optional,default=-1"`
	Published int `form:"published,optional,default=-1"` // -1:全部 0:未发布 1:已发布
}

type AdminEventNewsListResp struct {
	Code    int             `json:"code"`
	Success bool            `json:"success"`
	Message string          `json:"message"`
	Total   int64           `json:"total"`
	List    []EventNewsInfo `json:"list"`
}

type AdminEventNewsMatchCreateReq struct {
	EventId        int64  `json:"event_id"`
	RoundName      string `json:"round_name"`
	RoundOrder     int    `json:"round_order"`
	MatchOrder     int    `json:"match_order"`
	StartTime      string `json:"start_time,optional"`
	Status         int    `json:"status"`
	BestOf         int    `json:"best_of,optional"`
	HomePlayerId   int64  `json:"home_player_id,optional"`
	HomePlayerName string `json:"home_player_name,optional"`
	AwayPlayerId   int64  `json:"away_player_id,optional"`
	AwayPlayerName string `json:"away_player_name,optional"`
	HomeScore      int    `json:"home_score,optional"`
	AwayScore      int    `json:"away_score,optional"`
	WinnerSide     int    `json:"winner_side,optional"`
	IsPlaceholder  bool   `json:"is_placeholder,optional"`
	SourceType     string `json:"source_type,optional"`
	SourceMatchId  string `json:"source_match_id,optional"`
}

type AdminEventNewsMatchIdReq struct {
	MatchId int64 `json:"match_id"`
}

type AdminEventNewsMatchListReq struct {
	EventId int64 `form:"event_id"`
}

type AdminEventNewsMatchListResp struct {
	Code    int                  `json:"code"`
	Success bool                 `json:"success"`
	Message string               `json:"message"`
	List    []EventNewsMatchInfo `json:"list"`
}

type AdminEventNewsMatchUpdateReq struct {
	MatchId        int64  `json:"match_id"`
	EventId        int64  `json:"event_id"`
	RoundName      string `json:"round_name"`
	RoundOrder     int    `json:"round_order"`
	MatchOrder     int    `json:"match_order"`
	StartTime      string `json:"start_time,optional"`
	Status         int    `json:"status"`
	BestOf         int    `json:"best_of,optional"`
	HomePlayerId   int64  `json:"home_player_id,optional"`
	HomePlayerName string `json:"home_player_name,optional"`
	AwayPlayerId   int64  `json:"away_player_id,optional"`
	AwayPlayerName string `json:"away_player_name,optional"`
	HomeScore      int    `json:"home_score,optional"`
	AwayScore      int    `json:"away_score,optional"`
	WinnerSide     int    `json:"winner_side,optional"`
	IsPlaceholder  bool   `json:"is_placeholder,optional"`
	SourceType     string `json:"source_type,optional"`
	SourceMatchId  string `json:"source_match_id,optional"`
}

type AdminEventNewsPublishReq struct {
	EventId   int64 `json:"event_id"`
	Published bool  `json:"published"`
}

type AdminEventNewsUpdateReq struct {
	EventId        int64  `json:"event_id"`
	Title          string `json:"title"`
	Summary        string `json:"summary,optional"`
	Content        string `json:"content,optional"`
	CoverImage     string `json:"cover_image,optional"`
	SourceType     string `json:"source_type,optional"`
	SourceName     string `json:"source_name,optional"`
	SourceUrl      string `json:"source_url,optional"`
	Published      bool   `json:"published,optional"`
	SortTime       string `json:"sort_time,optional"`
	TournamentId   int64  `json:"tournament_id,optional"`
	TournamentName string `json:"tournament_name"`
	GameType       int    `json:"game_type"`
	Description    string `json:"description,optional"`
	Country        string `json:"country,optional"`
	City           string `json:"city,optional"`
	Venue          string `json:"venue,optional"`
	StartDate      string `json:"start_date"`
	EndDate        string `json:"end_date,optional"`
	StartTime      string `json:"start_time,optional"`
	EndTime        string `json:"end_time,optional"`
	Status         int    `json:"status"`
}

type AdminExistsResp struct {
	Code    int    `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
	Exists  bool   `json:"exists"`
}

type AdminFeedbackTicketInfo struct {
	Id            int64  `json:"id"`
	UserId        int64  `json:"user_id,optional"`
	Source        string `json:"source"`
	SourceText    string `json:"source_text"`
	Category      string `json:"category"`
	CategoryText  string `json:"category_text"`
	Content       string `json:"content"`
	Contact       string `json:"contact"`
	Status        int    `json:"status"`
	StatusText    string `json:"status_text"`
	HandlerId     int64  `json:"handler_id,optional"`
	ProcessResult string `json:"process_result,optional"`
	ProcessedAt   string `json:"processed_at,optional"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type AdminFeedbackTicketListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Status   int    `form:"status,optional,default=-1"` // -1:全部 1:待处理 2:处理中 3:已办结 4:已关闭
	Category string `form:"category,optional"`
	Source   string `form:"source,optional"`
}

type AdminFeedbackTicketListResp struct {
	Code    int                       `json:"code"`
	Success bool                      `json:"success"`
	Message string                    `json:"message"`
	Total   int64                     `json:"total"`
	List    []AdminFeedbackTicketInfo `json:"list"`
}

type AdminFeedbackTicketProcessReq struct {
	TicketId      int64  `json:"ticket_id"`
	Status        int    `json:"status"` // 2:处理中 3:已办结 4:已关闭
	ProcessResult string `json:"process_result,optional"`
}

type AdminInfo struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Role     string `json:"role"`
}

type AdminInitReq struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	SetupToken string `json:"setup_token"`
}

type AdminInitResp struct {
	Code    int    `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type AdminLoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AdminLoginResp struct {
	Code     int        `json:"code"`
	Success  bool       `json:"success"`
	Message  string     `json:"message"`
	Token    string     `json:"token"`
	UserInfo *AdminInfo `json:"userInfo"`
}

type AdminMatchInfo struct {
	Id            int64  `json:"id"`
	GameType      int    `json:"game_type"`
	GameTypeName  string `json:"game_type_name"`
	Player1Name   string `json:"player1_name"`
	Player2Name   string `json:"player2_name"`
	MyScore       int    `json:"my_score"`
	OpponentScore int    `json:"opponent_score"`
	Status        int    `json:"status"`
	StatusText    string `json:"status_text"`
	Result        *int   `json:"result,omitempty"`
	WinnerName    string `json:"winner_name"`
	MatchTime     string `json:"match_time"`
	CreatedAt     string `json:"created_at"`
}

type AdminMatchListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
	Status   int `form:"status,optional,default=-1"`    // -1:全部 1:进行中 2:已完成 3:已取消
	GameType int `form:"game_type,optional,default=-1"` // -1:全部 1:斯诺克 2:九球追分 3:中式八球 4:美式九球
}

type AdminMatchListResp struct {
	Code    int              `json:"code"`
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Total   int64            `json:"total"`
	List    []AdminMatchInfo `json:"list"`
}

type AdminMemberGrowthRules struct {
	PointsPerCompletedMatch int    `json:"points_per_completed_match"`
	DailyCap                int    `json:"daily_cap"`
	LevelThresholdLv2       int    `json:"level_threshold_lv2"`
	LevelThresholdLv3       int    `json:"level_threshold_lv3"`
	LevelThresholdLv4       int    `json:"level_threshold_lv4"`
	LevelThresholdLv5       int    `json:"level_threshold_lv5"`
	ExpireStrategy          string `json:"expire_strategy"`
}

type AdminMemberRankingRightsRules struct {
	OrdinaryUserAchievementEnabled bool `json:"ordinary_user_achievement_enabled"`
	DailyCap                       int  `json:"daily_cap"`
	DailyPositiveCap               int  `json:"daily_positive_cap"`
	Break50Score                   int  `json:"break_50_score"`
	GoldenBreakScore               int  `json:"golden_break_score"`
	BreakAndRunScore               int  `json:"break_and_run_score"`
	RunOutScore                    int  `json:"run_out_score"`
	Break100Score                  int  `json:"break_100_score"`
	NineOnBreakScore               int  `json:"nine_on_break_score"`
	Break147Score                  int  `json:"break_147_score"`
	Level1Multiplier               int  `json:"level1_multiplier"`
	Level2Multiplier               int  `json:"level2_multiplier"`
	Level3Multiplier               int  `json:"level3_multiplier"`
	Level4Multiplier               int  `json:"level4_multiplier"`
	Level5Multiplier               int  `json:"level5_multiplier"`
}

type AdminMemberRightsConfigResp struct {
	Code          int                           `json:"code"`
	Success       bool                          `json:"success"`
	Message       string                        `json:"message"`
	GrowthRules   AdminMemberGrowthRules        `json:"growth_rules"`
	RankingRights AdminMemberRankingRightsRules `json:"ranking_rights_rules"`
}

type AdminMemberRightsConfigUpdateReq struct {
	GrowthRules   AdminMemberGrowthRules        `json:"growth_rules"`
	RankingRights AdminMemberRankingRightsRules `json:"ranking_rights_rules"`
}

type AdminRecentMatch struct {
	Id            int64  `json:"id"`
	GameType      int    `json:"game_type"`
	GameTypeName  string `json:"game_type_name"`
	Player1Name   string `json:"player1_name"`
	Player2Name   string `json:"player2_name"`
	MyScore       int    `json:"my_score"`
	OpponentScore int    `json:"opponent_score"`
	Status        int    `json:"status"`
	CreatedAt     string `json:"created_at"`
}

type AdminRecentMatchesResp struct {
	Code    int                `json:"code"`
	Success bool               `json:"success"`
	Message string             `json:"message"`
	List    []AdminRecentMatch `json:"list"`
}

type AdminRecentUser struct {
	Id        int64  `json:"id"`
	Nickname  string `json:"nickname"`
	Phone     string `json:"phone"`
	CreatedAt string `json:"created_at"`
}

type AdminRecentUsersResp struct {
	Code    int               `json:"code"`
	Success bool              `json:"success"`
	Message string            `json:"message"`
	List    []AdminRecentUser `json:"list"`
}

type AdminReputationBaseRules struct {
	MaxScore         int `json:"max_score"`
	InitialScore     int `json:"initial_score"`
	BanThreshold     int `json:"ban_threshold"`
	BanDurationHours int `json:"ban_duration_hours"`
	MinScore         int `json:"min_score"`
}

type AdminReputationConfigResp struct {
	Code           int                           `json:"code"`
	Success        bool                          `json:"success"`
	Message        string                        `json:"message"`
	BaseRules      AdminReputationBaseRules      `json:"base_rules"`
	RecoveryRules  AdminReputationRecoveryRules  `json:"recovery_rules"`
	DetectionRules AdminReputationDetectionRules `json:"detection_rules"`
}

type AdminReputationConfigUpdateReq struct {
	BaseRules      AdminReputationBaseRules      `json:"base_rules"`
	RecoveryRules  AdminReputationRecoveryRules  `json:"recovery_rules"`
	DetectionRules AdminReputationDetectionRules `json:"detection_rules"`
}

type AdminReputationDetectionRules struct {
	DurationRules          []AdminReputationDurationRule   `json:"duration_rules"`
	SameOpponentRule       AdminReputationSameOpponentRule `json:"same_opponent_rule"`
	StackPenaltiesPerMatch bool                            `json:"stack_penalties_per_match"`
}

type AdminReputationDurationRule struct {
	GameType                int  `json:"game_type"`
	Enabled                 bool `json:"enabled"`
	MinMinutesPerRound      int  `json:"min_minutes_per_round"`
	MinTotalRounds          int  `json:"min_total_rounds"`
	MinTotalDurationMinutes int  `json:"min_total_duration_minutes"`
	PenaltyScore            int  `json:"penalty_score"`
}

type AdminReputationLogItem struct {
	Id              int64  `json:"id"`
	UserId          int64  `json:"user_id"`
	Nickname        string `json:"nickname"`
	MatchId         int64  `json:"match_id,optional"`
	ChangeType      string `json:"change_type"`
	ChangeTypeText  string `json:"change_type_text"`
	ReasonCode      string `json:"reason_code"`
	ReasonText      string `json:"reason_text"`
	ReasonDetail    string `json:"reason_detail,optional"`
	ChangeScore     int    `json:"change_score"`
	BeforeScore     int    `json:"before_score"`
	AfterScore      int    `json:"after_score"`
	OperatorAdminId int64  `json:"operator_admin_id,optional"`
	OperatorText    string `json:"operator_text"`
	CreatedAt       string `json:"created_at"`
}

type AdminReputationLogListReq struct {
	Page       int    `form:"page,default=1"`
	PageSize   int    `form:"page_size,default=20"`
	UserId     int64  `form:"user_id,optional"`
	ChangeType string `form:"change_type,optional"`
	ReasonCode string `form:"reason_code,optional"`
}

type AdminReputationLogListResp struct {
	Code    int                      `json:"code"`
	Success bool                     `json:"success"`
	Message string                   `json:"message"`
	Total   int64                    `json:"total"`
	List    []AdminReputationLogItem `json:"list"`
}

type AdminReputationRecoveryRules struct {
	Enabled         bool `json:"enabled"`
	RecoverPerHour  int  `json:"recover_per_hour"`
	RecoverMaxScore int  `json:"recover_max_score"`
}

type AdminReputationSameOpponentRule struct {
	Enabled             bool `json:"enabled"`
	WindowMinutes       int  `json:"window_minutes"`
	MaxMatches          int  `json:"max_matches"`
	PenaltyScore        int  `json:"penalty_score"`
	RequireSameGameType bool `json:"require_same_game_type"`
}

type AdminSocialPostInfo struct {
	Id            int64    `json:"id"`
	UserId        int64    `json:"user_id"`
	Nickname      string   `json:"nickname"`
	Avatar        string   `json:"avatar"`
	Content       string   `json:"content"`
	Images        []string `json:"images"`
	PostType      int      `json:"post_type"`
	MatchId       int64    `json:"match_id,omitempty"`
	LikesCount    int      `json:"likes_count"`
	CommentsCount int      `json:"comments_count"`
	Status        int      `json:"status"`
	StatusText    string   `json:"status_text"`
	RejectReason  string   `json:"reject_reason"`
	ReviewedAt    string   `json:"reviewed_at,optional"`
	ReviewedBy    int64    `json:"reviewed_by,optional"`
	CreatedAt     string   `json:"created_at"`
}

type AdminSocialPostListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
	Status   int `form:"status,default=-1"` // -1:全部 1:已发布 2:待审核 3:已拒绝
}

type AdminSocialPostListResp struct {
	Code    int                   `json:"code"`
	Success bool                  `json:"success"`
	Message string                `json:"message"`
	Total   int64                 `json:"total"`
	List    []AdminSocialPostInfo `json:"list"`
}

type AdminSocialPostReviewReq struct {
	PostId       int64  `json:"post_id"`
	Status       int    `json:"status"` // 1:通过 3:拒绝
	RejectReason string `json:"reject_reason,optional"`
}

type AdminUserInfo struct {
	Id              int64  `json:"id"`
	Phone           string `json:"phone"`
	Nickname        string `json:"nickname"`
	Avatar          string `json:"avatar"`
	Status          int    `json:"status"`
	ReputationScore int    `json:"reputation_score"`
	BanUntil        string `json:"ban_until,optional"`
	MemberStatus    string `json:"member_status"`
	MemberExpiresAt string `json:"member_expires_at,optional"`
	CreatedAt       string `json:"created_at"`
}

type AdminUserInfoResp struct {
	Code     int        `json:"code"`
	Success  bool       `json:"success"`
	Message  string     `json:"message"`
	UserInfo *AdminInfo `json:"userInfo"`
}

type AdminUserListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
	Status   int `form:"status,optional,default=-1"`
}

type AdminUserListResp struct {
	Code    int             `json:"code"`
	Success bool            `json:"success"`
	Message string          `json:"message"`
	Total   int64           `json:"total"`
	List    []AdminUserInfo `json:"list"`
}

type AdminUserUpdateStatusReq struct {
	UserId int64 `json:"user_id"`
	Status int   `json:"status"`
}

type AdminVenueInfo struct {
	Id            int64   `json:"id"`
	Name          string  `json:"name"`
	Address       string  `json:"address"`
	City          string  `json:"city"`
	District      string  `json:"district"`
	Latitude      float64 `json:"latitude"`
	Longitude     float64 `json:"longitude"`
	Phone         string  `json:"phone"`
	Images        string  `json:"images"`
	BusinessHours string  `json:"business_hours"`
	TableCount    int     `json:"table_count"`
	PriceRange    string  `json:"price_range"`
	Description   string  `json:"description"`
	Status        int     `json:"status"`
	GeoStatus     int     `json:"geo_status"`
	OwnerUserId   int64   `json:"owner_user_id"`
	RejectReason  string  `json:"reject_reason"`
	CreatedAt     string  `json:"created_at"`
}

type AdminVenueListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Status   int    `form:"status,default=-1"` // -1:全部 0:隐藏 1:已发布 2:待审核 3:已拒绝
	City     string `form:"city,optional"`
}

type AdminVenueListResp struct {
	Code    int              `json:"code"`
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Total   int64            `json:"total"`
	List    []AdminVenueInfo `json:"list"`
}

type AdminVenueReviewReq struct {
	VenueId      int64  `json:"venue_id"`
	Status       int    `json:"status"` // 1:通过 3:拒绝
	RejectReason string `json:"reject_reason,optional"`
}

type AdminVenueReviewResp struct {
	Code    int    `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type AdminVenueRewardConfigResp struct {
	Code                 int    `json:"code"`
	Success              bool   `json:"success"`
	Message              string `json:"message"`
	Enabled              bool   `json:"enabled"`
	PopupEnabled         bool   `json:"popup_enabled"`
	RewardDays           int    `json:"reward_days"`
	NewUserWindowDays    int    `json:"new_user_window_days"`
	WelcomeRewardEnabled bool   `json:"welcome_reward_enabled"`
	WelcomeRewardDays    int    `json:"welcome_reward_days"`
	StartAt              string `json:"start_at,optional"`
	EndAt                string `json:"end_at,optional"`
}

type AdminVenueRewardConfigUpdateReq struct {
	Enabled              bool   `json:"enabled"`
	PopupEnabled         bool   `json:"popup_enabled"`
	RewardDays           int    `json:"reward_days"`
	NewUserWindowDays    int    `json:"new_user_window_days"`
	WelcomeRewardEnabled bool   `json:"welcome_reward_enabled"`
	WelcomeRewardDays    int    `json:"welcome_reward_days"`
	StartAt              string `json:"start_at,optional"`
	EndAt                string `json:"end_at,optional"`
}

type AdminVenueRewardRecordInfo struct {
	Id                    int64  `json:"id"`
	UserId                int64  `json:"user_id"`
	UserNickname          string `json:"user_nickname"`
	UserPhone             string `json:"user_phone"`
	VenueId               int64  `json:"venue_id"`
	VenueName             string `json:"venue_name"`
	RewardDays            int    `json:"reward_days"`
	MemberExpiresAtBefore string `json:"member_expires_at_before,optional"`
	MemberExpiresAtAfter  string `json:"member_expires_at_after"`
	GrantedAt             string `json:"granted_at"`
}

type AdminVenueRewardRecordListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type AdminVenueRewardRecordListResp struct {
	Code    int                          `json:"code"`
	Success bool                         `json:"success"`
	Message string                       `json:"message"`
	Total   int64                        `json:"total"`
	List    []AdminVenueRewardRecordInfo `json:"list"`
}

type AdminWriteResp struct {
	Code         int    `json:"code"`
	Success      bool   `json:"success"`
	Message      string `json:"message"`
	EventId      int64  `json:"event_id,optional"`
	TournamentId int64  `json:"tournament_id,optional"`
}

type BindPhoneReq struct {
	Phone   string `json:"phone"`
	SmsCode string `json:"sms_code"`
}

type BindPhoneResp struct {
	Success       bool   `json:"success"`
	Message       string `json:"message"`
	MergedAccount bool   `json:"merged_account"`
}

type BlacklistFriendReq struct {
	FriendUserId int64 `json:"friend_user_id"`
}

type CancelMatchReq struct {
	MatchId int64 `json:"match_id"`
}

type ChallengeInfo struct {
	Id           int64  `json:"id"`
	FromUserId   int64  `json:"from_user_id"`
	FromNickname string `json:"from_nickname"`
	FromAvatar   string `json:"from_avatar"`
	ToUserId     int64  `json:"to_user_id"`
	ToNickname   string `json:"to_nickname"`
	ToAvatar     string `json:"to_avatar"`
	GameType     int    `json:"game_type"`
	Message      string `json:"message"`
	Status       int    `json:"status"`
	CreatedAt    string `json:"created_at"`
}

type CommentPostReq struct {
	PostId  int64  `json:"post_id"`
	Content string `json:"content"`
}

type CommonResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type CreateFeedbackTicketReq struct {
	Source   string `json:"source,optional,default=app"`        // app/website
	Category string `json:"category,optional,default=feedback"` // feedback/complaint/report
	Content  string `json:"content"`
	Contact  string `json:"contact,optional"`
}

type CreateFeedbackTicketResp struct {
	Success  bool   `json:"success"`
	Message  string `json:"message"`
	TicketId int64  `json:"ticket_id"`
}

type CreateMemberSubscriptionOrderReq struct {
	PlanCode   string `json:"plan_code"`
	PayChannel string `json:"pay_channel"`
}

type CreateMemberSubscriptionOrderResp struct {
	Success            bool                `json:"success"`
	Message            string              `json:"message"`
	OrderNo            string              `json:"order_no"`
	PayChannel         string              `json:"pay_channel"`
	PlanCode           string              `json:"plan_code"`
	PlanName           string              `json:"plan_name"`
	AmountFen          int                 `json:"amount_fen"`
	AmountYuan         string              `json:"amount_yuan"`
	Status             string              `json:"status"`
	AlipayOrderString  string              `json:"alipay_order_string,optional"`
	WechatAppPayParams *WechatAppPayParams `json:"wechat_app_pay_params,optional"`
}

type CreatePostReq struct {
	Content  string   `json:"content"`
	Images   []string `json:"images,optional"`
	PostType int      `json:"post_type"`
	MatchId  int64    `json:"match_id,optional"`
}

type CreatePostResp struct {
	Success bool  `json:"success"`
	PostId  int64 `json:"post_id"`
}

type CreateTournamentReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	GameType    int    `json:"game_type"`
	Format      int    `json:"format"`
	MaxPlayers  int    `json:"max_players"`
	City        string `json:"city,optional"`
	VenueName   string `json:"venue_name,optional"`
	StartTime   string `json:"start_time"`
}

type CreateTournamentResp struct {
	Success      bool  `json:"success"`
	TournamentId int64 `json:"tournament_id"`
}

type CreateVenueReq struct {
	Name     string `json:"name"`
	Address  string `json:"address"`
	City     string `json:"city"`
	District string `json:"district,optional"`
}

type CreateVenueResp struct {
	Success bool   `json:"success"`
	VenueId int64  `json:"venue_id"`
	Message string `json:"message"`
}

type CurrentMatchInfo struct {
	Id                        int64  `json:"id"`
	GameType                  int    `json:"game_type"`
	GameTypeName              string `json:"game_type_name"`
	GameMode                  string `json:"game_mode"`
	ViewerRole                string `json:"viewer_role,optional"`
	RefereeBound              bool   `json:"referee_bound,optional"`
	RefereeUserId             int64  `json:"referee_user_id,optional"`
	RefereeName               string `json:"referee_name,optional"`
	CanScore                  bool   `json:"can_score,optional"`
	CanUndo                   bool   `json:"can_undo,optional"`
	CanFinish                 bool   `json:"can_finish,optional"`
	OpponentId                int64  `json:"opponent_id,optional"`
	OpponentName              string `json:"opponent_name"`
	OpponentAvatar            string `json:"opponent_avatar,optional"`
	MyScore                   int    `json:"my_score"`
	OpponentScore             int    `json:"opponent_score"`
	CurrentFrameStarted       bool   `json:"current_frame_started,optional"`
	CurrentFrameMyScore       int    `json:"current_frame_my_score,optional"`
	CurrentFrameOpponentScore int    `json:"current_frame_opponent_score,optional"`
	CurrentRound              int    `json:"current_round"`
	ServerRevision            int64  `json:"server_revision"`
	MatchTime                 string `json:"match_time"`
	DurationSeconds           int64  `json:"duration_seconds"` // 对局已持续秒数
}

type DeleteFriendReq struct {
	FriendUserId int64 `json:"friend_user_id"`
}

type DurationStats struct {
	AverageSeconds int `json:"average_seconds"`
	FastestSeconds int `json:"fastest_seconds"`
	LongestSeconds int `json:"longest_seconds"`
	TotalMatches   int `json:"total_matches"`
}

type EndRoundReq struct {
	MatchId        int64  `json:"match_id"`
	Winner         int    `json:"winner"`                   // 1=我 2=对手
	WinType        string `json:"win_type,optional"`        // 获胜方式
	Score          int    `json:"score,optional,default=1"` // 获胜得分，默认1分
	ClientActionId string `json:"client_action_id"`
	BaseRevision   int64  `json:"base_revision"`
}

type EndRoundResp struct {
	Accepted                  bool              `json:"accepted"`
	Success                   bool              `json:"success"`
	ClientActionId            string            `json:"client_action_id,optional"`
	ServerRevision            int64             `json:"server_revision"`
	Snapshot                  MatchSyncSnapshot `json:"snapshot"`
	RoundNo                   int               `json:"round_no"`
	CurrentFrameStarted       bool              `json:"current_frame_started,optional"`
	CurrentFrameMyScore       int               `json:"current_frame_my_score,optional"`
	CurrentFrameOpponentScore int               `json:"current_frame_opponent_score,optional"`
	MyScore                   int               `json:"my_score"`
	OpponentScore             int               `json:"opponent_score"`
}

type EquipTitleReq struct {
	TitleId int64 `json:"title_id"`
	Equip   bool  `json:"equip"`
}

type EventNewsInfo struct {
	Id               int64  `json:"id"`
	Title            string `json:"title"`
	SourceType       string `json:"source_type"`
	SourceName       string `json:"source_name"`
	SourceUrl        string `json:"source_url"`
	CoverImage       string `json:"cover_image"`
	Summary          string `json:"summary"`
	Content          string `json:"content"`
	Description      string `json:"description"`
	TournamentId     int64  `json:"tournament_id"`
	TournamentName   string `json:"tournament_name"`
	GameType         int    `json:"game_type"`
	Country          string `json:"country"`
	City             string `json:"city"`
	Venue            string `json:"venue"`
	StartDate        string `json:"start_date"`
	EndDate          string `json:"end_date"`
	StartTime        string `json:"start_time,optional"`
	EndTime          string `json:"end_time,optional"`
	Status           int    `json:"status"` // 0:即将开始 1:进行中 2:已结束 3:已取消
	CurrentRoundText string `json:"current_round_text"`
	LatestResultText string `json:"latest_result_text"`
	MatchCount       int    `json:"match_count"`
	SortTime         string `json:"sort_time"`
	Published        bool   `json:"published"`
	PublishedAt      string `json:"published_at"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

type EventNewsMatchInfo struct {
	Id                  int64  `json:"id"`
	EventId             int64  `json:"event_id"`
	TournamentId        int64  `json:"tournament_id"`
	SourceType          string `json:"source_type"`
	SourceMatchId       string `json:"source_match_id"`
	RoundName           string `json:"round_name"`
	RoundOrder          int    `json:"round_order"`
	MatchOrder          int    `json:"match_order"`
	StartTime           string `json:"start_time"`
	Status              int    `json:"status"`
	BestOf              int    `json:"best_of"`
	HomePlayerId        int64  `json:"home_player_id"`
	HomePlayerName      string `json:"home_player_name"`
	HomePlayerFirstName string `json:"home_player_first_name,optional"`
	HomePlayerLastName  string `json:"home_player_last_name,optional"`
	HomePlayerFlagEmoji string `json:"home_player_flag_emoji,optional"`
	HomePlayerAvatar    string `json:"home_player_avatar,optional"`
	AwayPlayerId        int64  `json:"away_player_id"`
	AwayPlayerName      string `json:"away_player_name"`
	AwayPlayerFirstName string `json:"away_player_first_name,optional"`
	AwayPlayerLastName  string `json:"away_player_last_name,optional"`
	AwayPlayerFlagEmoji string `json:"away_player_flag_emoji,optional"`
	AwayPlayerAvatar    string `json:"away_player_avatar,optional"`
	HomeScore           int    `json:"home_score"`
	AwayScore           int    `json:"away_score"`
	WinnerSide          int    `json:"winner_side"`
	IsPlaceholder       bool   `json:"is_placeholder"`
	CreatedAt           string `json:"created_at"`
	UpdatedAt           string `json:"updated_at"`
}

type FavoriteVenueRewardStatusResp struct {
	Success            bool   `json:"success"`
	Enabled            bool   `json:"enabled"`
	PopupEnabled       bool   `json:"popup_enabled"`
	RewardDays         int    `json:"reward_days"`
	NewUserWindowDays  int    `json:"new_user_window_days"`
	Status             string `json:"status"`
	MemberExpiresAt    string `json:"member_expires_at,optional"`
	SubmittedVenueId   int64  `json:"submitted_venue_id,optional"`
	SubmittedVenueName string `json:"submitted_venue_name,optional"`
	RejectReason       string `json:"reject_reason,optional"`
}

type FinishMatchReq struct {
	MatchId        int64  `json:"match_id"`
	Remark         string `json:"remark,optional"`
	ClientActionId string `json:"client_action_id"`
	BaseRevision   int64  `json:"base_revision"`
}

type FinishMatchResp struct {
	Accepted       bool              `json:"accepted"`
	Success        bool              `json:"success"`
	Result         int               `json:"result"` // 1=胜利 2=失败 3=平局
	ClientActionId string            `json:"client_action_id,optional"`
	ServerRevision int64             `json:"server_revision"`
	Snapshot       MatchSyncSnapshot `json:"snapshot"`
	MyScore        int               `json:"my_score"`
	OpponentScore  int               `json:"opponent_score"`
}

type FollowReq struct {
	TargetUserId int64 `json:"target_user_id"`
}

type FollowUserInfo struct {
	UserId      int64  `json:"user_id"`
	Nickname    string `json:"nickname"`
	Avatar      string `json:"avatar"`
	RankName    string `json:"rank_name"`
	IsFollowing bool   `json:"is_following"`
}

type FriendInfo struct {
	Id        int64  `json:"id"`
	UserId    int64  `json:"user_id"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	RankLevel int    `json:"rank_level"`
	RankName  string `json:"rank_name"`
	CreatedAt string `json:"created_at"`
}

type FriendRequestInfo struct {
	Id         int64  `json:"id"`
	FromUserId int64  `json:"from_user_id"`
	Nickname   string `json:"nickname"`
	Avatar     string `json:"avatar"`
	Message    string `json:"message"`
	Status     int    `json:"status"`
	CreatedAt  string `json:"created_at"`
}

type GameTypeStats struct {
	GameType     int     `json:"game_type"`
	GameTypeName string  `json:"game_type_name"`
	TotalMatches int     `json:"total_matches"`
	Wins         int     `json:"wins"`
	Losses       int     `json:"losses"`
	WinRate      float64 `json:"win_rate"`
	HighestScore int     `json:"highest_score"`
}

type GetAchievementListReq struct {
	Category string `form:"category,optional"`
}

type GetAchievementListResp struct {
	Success bool             `json:"success"`
	List    []AchievementDef `json:"list"`
}

type GetCurrentMatchResp struct {
	Success bool              `json:"success"`
	Match   *CurrentMatchInfo `json:"match"`
}

type GetCurrentSeasonResp struct {
	Success bool        `json:"success"`
	Season  *SeasonInfo `json:"season"`
}

type GetEventNewsListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Status   int    `form:"status,optional,default=-1"`
	GameType int    `form:"game_type,optional"`
	City     string `form:"city,optional"`
	Year     int    `form:"year,optional"`
	From     string `form:"from,optional"`
	To       string `form:"to,optional"`
}

type GetEventNewsListResp struct {
	Success bool            `json:"success"`
	Total   int64           `json:"total"`
	List    []EventNewsInfo `json:"list"`
}

type GetEventNewsViewReq struct {
	EventId int64 `form:"event_id"`
}

type GetEventNewsViewResp struct {
	Success    bool                 `json:"success"`
	EventNews  *EventNewsInfo       `json:"event_news"`
	Tournament *TournamentInfo      `json:"tournament"`
	Matches    []EventNewsMatchInfo `json:"matches"`
}

type GetFollowListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type GetFollowListResp struct {
	Success bool             `json:"success"`
	Total   int64            `json:"total"`
	List    []FollowUserInfo `json:"list"`
}

type GetFriendListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Keyword  string `form:"keyword,optional"`
}

type GetFriendListResp struct {
	Success bool         `json:"success"`
	Total   int64        `json:"total"`
	List    []FriendInfo `json:"list"`
}

type GetFriendRequestsReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type GetFriendRequestsResp struct {
	Success bool                `json:"success"`
	Total   int64               `json:"total"`
	List    []FriendRequestInfo `json:"list"`
}

type GetGlossaryReq struct {
	Category string `form:"category,optional"`
}

type GetGlossaryResp struct {
	Success bool               `json:"success"`
	List    []GlossaryItemInfo `json:"list"`
}

type GetLeaderboardReq struct {
	GameType int `form:"game_type,optional,default=3"`
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type GetLeaderboardResp struct {
	Success   bool              `json:"success"`
	Total     int64             `json:"total"`
	TopThree  []LeaderboardItem `json:"top_three"`  // 前三名
	MyRanking *LeaderboardItem  `json:"my_ranking"` // 我的排名
	List      []LeaderboardItem `json:"list"`       // 第4名开始的列表
}

type GetMatchDetailReq struct {
	MatchId int64 `form:"match_id"`
}

type GetMatchDetailResp struct {
	Success bool            `json:"success"`
	Match   MatchDetailData `json:"match"`
}

type GetMatchDurationStatsReq struct {
	GameType int `form:"game_type,optional"`
}

type GetMatchDurationStatsResp struct {
	Success bool           `json:"success"`
	Stats   *DurationStats `json:"stats"`
}

type GetMatchQRCodeResp struct {
	Success    bool   `json:"success"`
	QrcodeData string `json:"qrcode_data"` // 二维码内容JSON: {"user_id":xxx,"nickname":"xxx","avatar":"xxx","ts":xxx}
}

type GetMatchRefereeQRCodeReq struct {
	MatchId int64 `form:"match_id"`
}

type GetMatchRefereeQRCodeResp struct {
	Success          bool   `json:"success"`
	QrcodeData       string `json:"qrcode_data"`
	ExpiresInSeconds int64  `json:"expires_in_seconds"`
}

type GetMatchShareDataReq struct {
	MatchId int64 `form:"match_id"`
}

type GetMatchShareDataResp struct {
	Success bool            `json:"success"`
	Data    *MatchShareData `json:"data"`
}

type GetMemberPlansResp struct {
	Success     bool             `json:"success"`
	CurrentTime string           `json:"current_time"`
	Plans       []MemberPlanInfo `json:"plans"`
}

type GetMemberStatusResp struct {
	Success               bool   `json:"success"`
	IsActive              bool   `json:"is_active"`
	CurrentTime           string `json:"current_time"`
	PlanCode              string `json:"plan_code,optional"`
	PlanName              string `json:"plan_name,optional"`
	MemberExpiresAt       string `json:"member_expires_at,optional"`
	GrowthLevel           int    `json:"growth_level,optional"`
	GrowthPoints          int    `json:"growth_points,optional"`
	TodayGrowthCount      int    `json:"today_growth_count,optional"`
	GrowthDailyCap        int    `json:"growth_daily_cap,optional"`
	GrowthFrozen          bool   `json:"growth_frozen,optional"`
	NextGrowthLevel       int    `json:"next_growth_level,optional"`
	NextGrowthLevelPoints int    `json:"next_growth_level_points,optional"`
	RemainingGrowthPoints int    `json:"remaining_growth_points,optional"`
}

type GetMemberSubscriptionOrderStatusReq struct {
	OrderNo string `form:"order_no"`
}

type GetMemberSubscriptionOrderStatusResp struct {
	Success               bool   `json:"success"`
	Message               string `json:"message,optional"`
	OrderNo               string `json:"order_no"`
	PayChannel            string `json:"pay_channel"`
	PlanCode              string `json:"plan_code"`
	PlanName              string `json:"plan_name"`
	AmountFen             int    `json:"amount_fen"`
	AmountYuan            string `json:"amount_yuan"`
	Status                string `json:"status"`
	PaidAt                string `json:"paid_at,optional"`
	MemberExpiresAtBefore string `json:"member_expires_at_before,optional"`
	MemberExpiresAtAfter  string `json:"member_expires_at_after,optional"`
}

type GetMyCheckinsReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type GetMyCheckinsResp struct {
	Success bool               `json:"success"`
	Total   int64              `json:"total"`
	List    []VenueCheckinInfo `json:"list"`
}

type GetMySeasonRecordReq struct {
	SeasonId int64 `form:"season_id,optional"`
	GameType int   `form:"game_type,optional,default=3"`
}

type GetMySeasonRecordResp struct {
	Success bool              `json:"success"`
	Record  *SeasonRecordInfo `json:"record"`
}

type GetMyTournamentsReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
	Status   int `form:"status,optional"`
}

type GetNearbyVenuesReq struct {
	Latitude  float64 `form:"latitude"`
	Longitude float64 `form:"longitude"`
	Radius    int     `form:"radius,optional,default=5000"`
	Limit     int     `form:"limit,optional,default=10"`
}

type GetNotificationListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Type     string `form:"type,optional"`
}

type GetNotificationListResp struct {
	Success bool               `json:"success"`
	Total   int64              `json:"total"`
	List    []NotificationInfo `json:"list"`
}

type GetOngoingMatchesReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type GetOngoingMatchesResp struct {
	Success bool               `json:"success"`
	Total   int64              `json:"total"`
	List    []OngoingMatchItem `json:"list"`
}

type GetOpponentListReq struct {
	Page         int    `form:"page,default=1"`
	PageSize     int    `form:"page_size,default=20"`
	Keyword      string `form:"keyword,optional"`
	TargetUserId int64  `form:"target_user_id,optional"`
}

type GetOpponentListResp struct {
	Success        bool                 `json:"success"`
	Message        string               `json:"message,optional"`
	Hidden         bool                 `json:"hidden"`
	TotalOpponents int                  `json:"total_opponents"` // 总对手数
	TotalWins      int                  `json:"total_wins"`      // 总胜场
	Total          int64                `json:"total"`
	List           []OpponentRecordItem `json:"list"`
}

type GetOpponentStrengthResp struct {
	Success bool                   `json:"success"`
	List    []OpponentStrengthItem `json:"list"`
}

type GetPendingChallengesResp struct {
	Success bool            `json:"success"`
	List    []ChallengeInfo `json:"list"`
}

type GetPostCommentsReq struct {
	PostId   int64 `form:"post_id"`
	Page     int   `form:"page,default=1"`
	PageSize int   `form:"page_size,default=20"`
}

type GetPostCommentsResp struct {
	Success bool              `json:"success"`
	Total   int64             `json:"total"`
	List    []PostCommentInfo `json:"list"`
}

type GetPostListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type GetPostListResp struct {
	Success bool             `json:"success"`
	Total   int64            `json:"total"`
	List    []SocialPostInfo `json:"list"`
}

type GetPublicMatchDetailReq struct {
	MatchId int64 `form:"match_id"`
}

type GetPublicMatchDetailResp struct {
	Success bool                   `json:"success"`
	Match   *PublicMatchDetailData `json:"match"`
}

type GetQiniuUploadTokenReq struct {
	FileExt string `form:"file_ext,optional"`
}

type GetQiniuUploadTokenResp struct {
	Success     bool   `json:"success"`
	Message     string `json:"message"`
	UploadToken string `json:"upload_token,optional"`
	Key         string `json:"key,optional"`
	UploadUrl   string `json:"upload_url,optional"`
	Domain      string `json:"domain,optional"`
}

type GetRankListReq struct {
	GameType int `form:"game_type,optional,default=3"`
}

type GetRankListResp struct {
	Success bool       `json:"success"`
	List    []RankItem `json:"list"`
}

type GetRankScoreTrendReq struct {
	Limit    int `form:"limit,optional,default=30"`
	GameType int `form:"game_type,optional,default=3"`
}

type GetRankScoreTrendResp struct {
	Success bool         `json:"success"`
	List    []TrendPoint `json:"list"`
}

type GetRecentTrendReq struct {
	Limit    int `form:"limit,optional,default=30"`
	GameType int `form:"game_type,optional"`
}

type GetRecentTrendResp struct {
	Success bool         `json:"success"`
	List    []TrendPoint `json:"list"`
}

type GetRuleCategoriesResp struct {
	Success bool               `json:"success"`
	List    []RuleCategoryInfo `json:"list"`
}

type GetRuleContentReq struct {
	Category    string `form:"category"`
	ContentType string `form:"content_type"`
}

type GetRuleContentResp struct {
	Success bool              `json:"success"`
	List    []RuleContentItem `json:"list"`
}

type GetSeasonLeaderboardReq struct {
	SeasonId int64 `form:"season_id,optional"`
	GameType int   `form:"game_type,optional,default=3"`
	Page     int   `form:"page,default=1"`
	PageSize int   `form:"page_size,default=20"`
}

type GetSeasonLeaderboardResp struct {
	Success bool                    `json:"success"`
	Season  *SeasonInfo             `json:"season"`
	Total   int64                   `json:"total"`
	List    []SeasonLeaderboardItem `json:"list"`
}

type GetSeasonReportReq struct {
	SeasonId int64 `form:"season_id"`
	GameType int   `form:"game_type,optional,default=3"`
}

type GetSeasonReportResp struct {
	Success bool              `json:"success"`
	Report  *SeasonReportData `json:"report"`
}

type GetSingleHighScoreReq struct {
	GameType int `form:"game_type,optional"`
	Limit    int `form:"limit,optional,default=10"`
}

type GetSingleHighScoreResp struct {
	Success bool                    `json:"success"`
	List    []SingleHighScoreRecord `json:"list"`
}

type GetStatsByGameTypeResp struct {
	Success bool            `json:"success"`
	List    []GameTypeStats `json:"list"`
}

type GetTournamentBracketReq struct {
	TournamentId int64 `form:"tournament_id"`
}

type GetTournamentBracketResp struct {
	Success     bool                     `json:"success"`
	Matches     []TournamentBracketMatch `json:"matches"`
	TotalRounds int                      `json:"total_rounds"`
}

type GetTournamentDetailReq struct {
	TournamentId int64 `form:"tournament_id"`
}

type GetTournamentDetailResp struct {
	Success      bool                    `json:"success"`
	Tournament   *TournamentInfo         `json:"tournament"`
	Participants []TournamentParticipant `json:"participants"`
}

type GetTournamentListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"page_size,default=20"`
	Status   int    `form:"status,optional"`
	GameType int    `form:"game_type,optional"`
	City     string `form:"city,optional"`
}

type GetTournamentListResp struct {
	Success bool             `json:"success"`
	Total   int64            `json:"total"`
	List    []TournamentInfo `json:"list"`
}

type GetTournamentShareDataReq struct {
	TournamentId int64 `form:"tournament_id"`
}

type GetTournamentShareDataResp struct {
	Success bool                 `json:"success"`
	Data    *TournamentShareData `json:"data"`
}

type GetUnreadCountResp struct {
	Success bool `json:"success"`
	Count   int  `json:"count"`
}

type GetUserAchievementsResp struct {
	Success bool             `json:"success"`
	Total   int              `json:"total"`
	List    []AchievementDef `json:"list"`
}

type GetUserInfoResp struct {
	Success  bool      `json:"success"`
	UserInfo *UserInfo `json:"user_info"`
}

type GetUserPrivacyResp struct {
	Success         bool `json:"success"`
	HideMatchRecord bool `json:"hide_match_record"`
}

type GetUserRankInfoReq struct {
	GameType int `form:"game_type,optional,default=3"`
}

type GetUserRankInfoResp struct {
	Success  bool      `json:"success"`
	RankInfo *RankInfo `json:"rank_info"`
}

type GetUserReputationResp struct {
	Success    bool   `json:"success"`
	Score      int    `json:"score"`
	Status     string `json:"status"`
	StatusText string `json:"status_text"`
	BanUntil   string `json:"ban_until,optional"`
}

type GetUserTitlesResp struct {
	Success bool        `json:"success"`
	List    []TitleInfo `json:"list"`
}

type GetVenueAreaOptionsReq struct {
	ParentId int64 `form:"parent_id,optional,default=0"`
}

type GetVenueAreaOptionsResp struct {
	Success bool              `json:"success"`
	List    []VenueAreaOption `json:"list"`
}

type GetVenueDetailReq struct {
	VenueId int64 `form:"venue_id"`
}

type GetVenueDetailResp struct {
	Success bool       `json:"success"`
	Venue   *VenueInfo `json:"venue"`
}

type GetVenueListReq struct {
	Page      int     `form:"page,default=1"`
	PageSize  int     `form:"page_size,default=20"`
	City      string  `form:"city,optional"`
	Latitude  float64 `form:"latitude,optional"`
	Longitude float64 `form:"longitude,optional"`
	SortBy    string  `form:"sort_by,optional,default=distance"`
}

type GetVenueListResp struct {
	Success bool        `json:"success"`
	Total   int64       `json:"total"`
	List    []VenueInfo `json:"list"`
}

type GlossaryItemInfo struct {
	Id       int64  `json:"id"`
	Title    string `json:"title"`
	Content  string `json:"content"`
	Category string `json:"category"`
}

type H2HHistoryReq struct {
	TargetUserId int64  `form:"target_user_id,optional"`
	OpponentId   int64  `form:"opponent_id,optional"`
	OpponentName string `form:"opponent_name,optional"`
	Page         int    `form:"page,default=1"`
	PageSize     int    `form:"page_size,default=20"`
	Result       int    `form:"result,optional"`
}

type H2HHistoryResp struct {
	Success bool            `json:"success"`
	Message string          `json:"message,optional"`
	Total   int64           `json:"total"`
	List    []MatchListItem `json:"list"`
}

type H2HOpponent struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}

type H2HStats struct {
	TotalMatches int     `json:"total_matches"`
	MyWins       int     `json:"my_wins"`
	OpponentWins int     `json:"opponent_wins"`
	WinRate      float64 `json:"win_rate"`
	AvgScoreDiff float64 `json:"avg_score_diff"`
	MaxWinStreak int     `json:"max_win_streak"`
}

type H2HStatsReq struct {
	TargetUserId int64  `form:"target_user_id,optional"`
	OpponentId   int64  `form:"opponent_id,optional"`
	OpponentName string `form:"opponent_name,optional"`
}

type H2HStatsResp struct {
	Success  bool         `json:"success"`
	Message  string       `json:"message,optional"`
	Opponent *H2HOpponent `json:"opponent"`
	Stats    *H2HStats    `json:"stats"`
}

type HandleChallengeReq struct {
	ChallengeId int64 `json:"challenge_id"`
}

type HandleFriendRequestReq struct {
	RequestId int64 `json:"request_id"`
}

type JoinMatchRefereeReq struct {
	MatchId   int64  `json:"match_id"`
	JoinToken string `json:"join_token"`
}

type JoinMatchRefereeResp struct {
	Success bool              `json:"success"`
	Message string            `json:"message,optional"`
	MatchId int64             `json:"match_id"`
	Match   *CurrentMatchInfo `json:"match,optional"`
}

type LeaderboardItem struct {
	Rank      int    `json:"rank"` // 排名
	UserId    int64  `json:"user_id"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	RankLevel int    `json:"rank_level"` // 段位等级
	RankName  string `json:"rank_name"`  // 段位名称
	RankScore int    `json:"rank_score"` // 排位分
	WinRate   int    `json:"win_rate"`   // 胜率百分比
}

type LoginByOauthReq struct {
	Provider  string `json:"provider"` // huawei
	OpenId    string `json:"open_id"`
	UnionId   string `json:"union_id,optional"`
	NickName  string `json:"nick_name,optional"`
	AvatarUrl string `json:"avatar_url,optional"`
	Platform  string `json:"platform,optional"`
}

type LoginByOauthResp struct {
	Success       bool      `json:"success"`
	AccessToken   string    `json:"access_token"`
	RefreshToken  string    `json:"refresh_token"`
	ExpiresIn     int64     `json:"expires_in"`
	NeedBindPhone bool      `json:"need_bind_phone"`
	UserInfo      *UserInfo `json:"user_info"`
}

type LoginReq struct {
	Phone   string `json:"phone"`
	SmsCode string `json:"sms_code"`
}

type LoginResp struct {
	Success      bool      `json:"success"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresIn    int64     `json:"expires_in"`
	UserInfo     *UserInfo `json:"user_info"`
}

type MatchAchievement struct {
	BreakClear    int `json:"break_clear"`    // 炸清次数
	ContinueClear int `json:"continue_clear"` // 接清次数
	GoldenBreak   int `json:"golden_break"`   // 金球数
	NineOnBreak   int `json:"nine_on_break"`  // 大金数
	Break50       int `json:"break_50"`       // 单杆50+
	Break100      int `json:"break_100"`      // 单杆100+
	Break147      int `json:"break_147"`      // 单杆147
}

type MatchDetailData struct {
	Id                            int64              `json:"id"`
	GameType                      int                `json:"game_type"`
	Status                        int                `json:"status"` // 1=进行中 2=已完成 3=已取消
	ServerRevision                int64              `json:"server_revision"`
	IsPlayer1                     bool               `json:"is_player1"` // 当前用户是否是创建者(用于视角判断)
	ViewerRole                    string             `json:"viewer_role,optional"`
	RefereeBound                  bool               `json:"referee_bound,optional"`
	RefereeUserId                 int64              `json:"referee_user_id,optional"`
	RefereeName                   string             `json:"referee_name,optional"`
	CanScore                      bool               `json:"can_score,optional"`
	CanUndo                       bool               `json:"can_undo,optional"`
	CanFinish                     bool               `json:"can_finish,optional"`
	MyScore                       int                `json:"my_score"`       // 从当前用户视角的分数
	OpponentScore                 int                `json:"opponent_score"` // 从当前用户视角的对手分数
	MyName                        string             `json:"my_name"`
	OpponentName                  string             `json:"opponent_name"`
	MyAvatar                      string             `json:"my_avatar"`
	OpponentAvatar                string             `json:"opponent_avatar"`
	MyWinRate                     float64            `json:"my_win_rate"`        // 我方胜率(百分比)
	OpponentWinRate               float64            `json:"opponent_win_rate"`  // 对手胜率(百分比)
	MyMaxScore                    int                `json:"my_max_score"`       // 我方单杆最高
	OpponentMaxScore              int                `json:"opponent_max_score"` // 对手单杆最高
	MyRankChange                  int                `json:"my_rank_change"`
	OpponentRankChange            int                `json:"opponent_rank_change"`
	MyRankDetails                 []RankDetail       `json:"my_rank_details"`
	CurrentFrameStarted           bool               `json:"current_frame_started,optional"`
	CurrentFrameMyScore           int                `json:"current_frame_my_score,optional"`
	CurrentFrameOpponentScore     int                `json:"current_frame_opponent_score,optional"`
	RedBallCount                  int                `json:"red_ball_count,optional"`
	SnookerClearanceStarted       bool               `json:"snooker_clearance_started,optional"`
	SnookerClearedColors          []int              `json:"snooker_cleared_colors,optional"`
	SnookerExpectedClearanceScore int                `json:"snooker_expected_clearance_score,optional"`
	SnookerClearanceCompleted     bool               `json:"snooker_clearance_completed,optional"`
	SummaryHighlights             []MatchSummaryItem `json:"summary_highlights,optional"`
	SummaryStats                  []MatchSummaryItem `json:"summary_stats,optional"`
	Achievements                  MatchAchievement   `json:"achievements"`
	CreatedAt                     string             `json:"created_at"`
}

type MatchFoulReq struct {
	MatchId        int64  `json:"match_id"`
	Actor          int    `json:"actor"`          // 犯规方
	Score          int    `json:"score,optional"` // 犯规加分，默认1
	ClientActionId string `json:"client_action_id"`
	BaseRevision   int64  `json:"base_revision"`
}

type MatchListItem struct {
	Id             int64  `json:"id"`
	OpponentId     int64  `json:"opponent_id"` // 对手ID（注册用户才有）
	GameType       int    `json:"game_type"`
	GameTypeName   string `json:"game_type_name"`
	OpponentName   string `json:"opponent_name"`
	OpponentAvatar string `json:"opponent_avatar"`
	MyScore        int    `json:"my_score"`
	OpponentScore  int    `json:"opponent_score"`
	Result         int    `json:"result"`
	MatchTime      string `json:"match_time"`
}

type MatchListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
	GameType int `form:"game_type,optional"`
	Result   int `form:"result,optional"`
}

type MatchListResp struct {
	Success bool            `json:"success"`
	Total   int64           `json:"total"`
	List    []MatchListItem `json:"list"`
}

type MatchScoreReq struct {
	MatchId        int64  `json:"match_id"`
	Actor          int    `json:"actor"` // 1=我 2=对手
	Score          int    `json:"score"` // 加的分数
	ClientActionId string `json:"client_action_id"`
	BaseRevision   int64  `json:"base_revision"`
}

type MatchScoreResp struct {
	Accepted                      bool              `json:"accepted"`
	Success                       bool              `json:"success"`
	Message                       string            `json:"message,optional"`
	ClientActionId                string            `json:"client_action_id,optional"`
	ServerRevision                int64             `json:"server_revision"`
	Snapshot                      MatchSyncSnapshot `json:"snapshot"`
	RedBallCount                  int               `json:"red_ball_count,optional"`
	SnookerClearanceStarted       bool              `json:"snooker_clearance_started,optional"`
	SnookerClearedColors          []int             `json:"snooker_cleared_colors,optional"`
	SnookerExpectedClearanceScore int               `json:"snooker_expected_clearance_score,optional"`
	SnookerClearanceCompleted     bool              `json:"snooker_clearance_completed,optional"`
	CurrentFrameStarted           bool              `json:"current_frame_started,optional"`
	CurrentFrameMyScore           int               `json:"current_frame_my_score,optional"`
	CurrentFrameOpponentScore     int               `json:"current_frame_opponent_score,optional"`
	MyScore                       int               `json:"my_score"`
	OpponentScore                 int               `json:"opponent_score"`
}

type MatchShareData struct {
	MatchId           int64              `json:"match_id"`
	GameType          int                `json:"game_type"`
	GameTypeName      string             `json:"game_type_name"`
	MyName            string             `json:"my_name"`
	MyAvatar          string             `json:"my_avatar"`
	MyScore           int                `json:"my_score"`
	OpponentName      string             `json:"opponent_name"`
	OpponentAvatar    string             `json:"opponent_avatar"`
	OpponentScore     int                `json:"opponent_score"`
	Result            string             `json:"result"`
	MatchTime         string             `json:"match_time"`
	RankChange        int                `json:"rank_change"`
	SummaryHighlights []MatchSummaryItem `json:"summary_highlights,optional"`
	SummaryStats      []MatchSummaryItem `json:"summary_stats,optional"`
}

type MatchSummaryItem struct {
	Label string `json:"label"`
	Value string `json:"value"`
	Desc  string `json:"desc,optional"`
	Icon  string `json:"icon,optional"`
	Tone  string `json:"tone,optional"`
}

type MatchSyncSnapshot struct {
	MatchId                       int64  `json:"match_id"`
	Status                        int    `json:"status"`
	ServerRevision                int64  `json:"server_revision"`
	ViewerRole                    string `json:"viewer_role,optional"`
	RefereeBound                  bool   `json:"referee_bound,optional"`
	RefereeUserId                 int64  `json:"referee_user_id,optional"`
	RefereeName                   string `json:"referee_name,optional"`
	CanScore                      bool   `json:"can_score,optional"`
	CanUndo                       bool   `json:"can_undo,optional"`
	CanFinish                     bool   `json:"can_finish,optional"`
	MyScore                       int    `json:"my_score"`
	OpponentScore                 int    `json:"opponent_score"`
	CurrentFrameStarted           bool   `json:"current_frame_started,optional"`
	CurrentFrameMyScore           int    `json:"current_frame_my_score,optional"`
	CurrentFrameOpponentScore     int    `json:"current_frame_opponent_score,optional"`
	CurrentRound                  int    `json:"current_round"`
	TotalRounds                   int    `json:"total_rounds"`
	RedBallCount                  int    `json:"red_ball_count,optional"`
	SnookerClearanceStarted       bool   `json:"snooker_clearance_started,optional"`
	SnookerClearedColors          []int  `json:"snooker_cleared_colors,optional"`
	SnookerExpectedClearanceScore int    `json:"snooker_expected_clearance_score,optional"`
	SnookerClearanceCompleted     bool   `json:"snooker_clearance_completed,optional"`
}

type MatchUndoReq struct {
	MatchId        int64  `json:"match_id"`
	ClientActionId string `json:"client_action_id"`
	BaseRevision   int64  `json:"base_revision"`
}

type MatchUndoResp struct {
	Accepted                  bool              `json:"accepted"`
	Success                   bool              `json:"success"`
	ClientActionId            string            `json:"client_action_id,optional"`
	ServerRevision            int64             `json:"server_revision"`
	Snapshot                  MatchSyncSnapshot `json:"snapshot"`
	CurrentFrameStarted       bool              `json:"current_frame_started,optional"`
	CurrentFrameMyScore       int               `json:"current_frame_my_score,optional"`
	CurrentFrameOpponentScore int               `json:"current_frame_opponent_score,optional"`
	MyScore                   int               `json:"my_score"`
	OpponentScore             int               `json:"opponent_score"`
	Message                   string            `json:"message"`
}

type MemberPlanInfo struct {
	PlanCode      string `json:"plan_code"`
	PlanName      string `json:"plan_name"`
	PriceFen      int    `json:"price_fen"`
	PriceYuan     string `json:"price_yuan"`
	DurationDays  int    `json:"duration_days"`
	DurationLabel string `json:"duration_label"`
	Description   string `json:"description"`
	Highlight     string `json:"highlight,optional"`
}

type NotificationIdReq struct {
	NotificationId int64 `json:"notification_id"`
}

type NotificationInfo struct {
	Id        int64  `json:"id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Data      string `json:"data"`
	IsRead    bool   `json:"is_read"`
	CreatedAt string `json:"created_at"`
}

type OngoingMatchItem struct {
	Id              int64  `json:"id"`
	GameType        int    `json:"game_type"`
	GameTypeName    string `json:"game_type_name"`
	Player1Id       int64  `json:"player1_id"` // 玩家1(创建者)ID
	Player1Name     string `json:"player1_name"`
	Player1Avatar   string `json:"player1_avatar"`
	Player2Id       int64  `json:"player2_id"` // 玩家2(对手)ID，0表示非注册用户
	Player2Name     string `json:"player2_name"`
	Player2Avatar   string `json:"player2_avatar"`
	Player1Score    int    `json:"player1_score"`
	Player2Score    int    `json:"player2_score"`
	CurrentRound    int    `json:"current_round"`
	MatchTime       string `json:"match_time"`       // 开始时间 ISO格式
	DurationSeconds int64  `json:"duration_seconds"` // 对局已持续秒数，由服务端计算
}

type OpponentItem struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Avatar     string `json:"avatar"`
	MatchCount int    `json:"match_count"`
}

type OpponentRecordItem struct {
	Id           int64   `json:"id"`
	Name         string  `json:"name"`
	Avatar       string  `json:"avatar"`
	TotalMatches int     `json:"total_matches"` // 总对局数
	Wins         int     `json:"wins"`          // 我方胜场
	Losses       int     `json:"losses"`        // 我方负场
	WinRate      float64 `json:"win_rate"`      // 胜率百分比
	LastMatchAt  string  `json:"last_match_at"` // 上次对局时间
}

type OpponentStrengthItem struct {
	RankRange string  `json:"rank_range"`
	Matches   int     `json:"matches"`
	Wins      int     `json:"wins"`
	WinRate   float64 `json:"win_rate"`
}

type PostCommentInfo struct {
	Id        int64  `json:"id"`
	UserId    int64  `json:"user_id"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
}

type PostIdReq struct {
	PostId int64 `json:"post_id"`
}

type PublicMatchDetailData struct {
	Id                       int64         `json:"id"`
	GameType                 int           `json:"game_type"`
	Status                   int           `json:"status"` // 1=进行中 2=已完成 3=已取消
	ServerRevision           int64         `json:"server_revision"`
	Player1Id                int64         `json:"player1_id"`
	Player1Name              string        `json:"player1_name"`
	Player1Avatar            string        `json:"player1_avatar"`
	Player2Id                int64         `json:"player2_id"`
	Player2Name              string        `json:"player2_name"`
	Player2Avatar            string        `json:"player2_avatar"`
	Player1Score             int           `json:"player1_score"`
	Player2Score             int           `json:"player2_score"`
	CurrentFramePlayer1Score int           `json:"current_frame_player1_score,optional"`
	CurrentFramePlayer2Score int           `json:"current_frame_player2_score,optional"`
	CurrentFrameStarted      bool          `json:"current_frame_started,optional"`
	CurrentRound             int           `json:"current_round"`
	TotalRounds              int           `json:"total_rounds"`
	DurationSeconds          int64         `json:"duration_seconds"`
	Rounds                   []RoundRecord `json:"rounds"` // 局记录
	CreatedAt                string        `json:"created_at"`
}

type RankDetail struct {
	Label string `json:"label"`
	Value int    `json:"value"`
}

type RankInfo struct {
	Level       int    `json:"level"`        // 段位等级 1-5
	Name        string `json:"name"`         // 段位名称
	Icon        string `json:"icon"`         // 段位图标URL
	RankScore   int    `json:"rank_score"`   // 当前排位分
	TotalWins   int    `json:"total_wins"`   // 总胜场
	TotalLosses int    `json:"total_losses"` // 总败场
	MaxStreak   int    `json:"max_streak"`   // 最高连胜
	NextLevel   int    `json:"next_level"`   // 下一段位等级
	NextName    string `json:"next_name"`    // 下一段位名称
	NextScore   int    `json:"next_score"`   // 晋级所需分数
	Progress    int    `json:"progress"`     // 晋级进度百分比
}

type RankItem struct {
	Level     int    `json:"level"`
	Name      string `json:"name"`
	Icon      string `json:"icon"`
	MinScore  int    `json:"min_score"`  // 晋升最低分
	IsCurrent bool   `json:"is_current"` // 是否当前段位
}

type RoundRecord struct {
	RoundNumber  int `json:"round_number"`
	Player1Score int `json:"player1_score"`
	Player2Score int `json:"player2_score"`
	Winner       int `json:"winner"` // 1=玩家1胜 2=玩家2胜
}

type RuleCategoryInfo struct {
	Category      string `json:"category"`
	Name          string `json:"name"`
	Description   string `json:"description"`
	RuleCount     int    `json:"rule_count"`
	FoulCount     int    `json:"foul_count"`
	GlossaryCount int    `json:"glossary_count"`
}

type RuleContentItem struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	SortOrder int    `json:"sort_order"`
}

type SearchOpponentReq struct {
	Keyword string `form:"keyword"`
}

type SearchOpponentResp struct {
	Success bool           `json:"success"`
	List    []OpponentItem `json:"list"`
}

type SearchRulesReq struct {
	Keyword string `form:"keyword"`
}

type SearchRulesResp struct {
	Success bool              `json:"success"`
	List    []RuleContentItem `json:"list"`
}

type SearchUserItem struct {
	UserId   int64  `json:"user_id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	RankName string `json:"rank_name"`
	IsFriend bool   `json:"is_friend"`
}

type SearchUserReq struct {
	Keyword string `form:"keyword"`
}

type SearchUserResp struct {
	Success bool             `json:"success"`
	List    []SearchUserItem `json:"list"`
}

type SeasonInfo struct {
	Id             int64   `json:"id"`
	Name           string  `json:"name"`
	StartDate      string  `json:"start_date"`
	EndDate        string  `json:"end_date"`
	Status         int     `json:"status"`
	RankResetRatio float64 `json:"rank_reset_ratio"`
}

type SeasonLeaderboardItem struct {
	Rank          int    `json:"rank"`
	UserId        int64  `json:"user_id"`
	Nickname      string `json:"nickname"`
	Avatar        string `json:"avatar"`
	RankScore     int    `json:"rank_score"`
	PeakScore     int    `json:"peak_score"`
	MatchesPlayed int    `json:"matches_played"`
	Wins          int    `json:"wins"`
}

type SeasonRecordInfo struct {
	SeasonId       int64  `json:"season_id"`
	SeasonName     string `json:"season_name"`
	StartRankScore int    `json:"start_rank_score"`
	EndRankScore   int    `json:"end_rank_score"`
	PeakRankScore  int    `json:"peak_rank_score"`
	MatchesPlayed  int    `json:"matches_played"`
	Wins           int    `json:"wins"`
	FinalRank      int    `json:"final_rank"`
}

type SeasonReportData struct {
	Record          *SeasonRecordInfo `json:"record"`
	RankTrend       []int             `json:"rank_trend"`
	WinRateByType   map[string]int    `json:"win_rate_by_type,omitempty"`
	TopAchievements []AchievementDef  `json:"top_achievements"`
}

type SendChallengeReq struct {
	ToUserId int64  `json:"to_user_id"`
	GameType int    `json:"game_type"`
	Message  string `json:"message,optional"`
}

type SendChallengeResp struct {
	Success     bool  `json:"success"`
	ChallengeId int64 `json:"challenge_id"`
}

type SendFriendRequestReq struct {
	ToUserId int64  `json:"to_user_id"`
	Message  string `json:"message,optional"`
}

type SendSmsReq struct {
	Phone string `json:"phone"`
	Scene string `json:"scene,optional,default=login"` // login/bind
}

type SendSmsResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type SingleHighScoreRecord struct {
	MatchId      int64  `json:"match_id"`
	Score        int    `json:"score"`
	GameType     int    `json:"game_type"`
	GameTypeName string `json:"game_type_name"`
	OpponentName string `json:"opponent_name"`
	Date         string `json:"date"`
}

type SocialPostInfo struct {
	Id            int64    `json:"id"`
	UserId        int64    `json:"user_id"`
	Nickname      string   `json:"nickname"`
	Avatar        string   `json:"avatar"`
	Content       string   `json:"content"`
	Images        []string `json:"images"`
	PostType      int      `json:"post_type"`
	MatchId       int64    `json:"match_id,omitempty"`
	LikesCount    int      `json:"likes_count"`
	CommentsCount int      `json:"comments_count"`
	IsLiked       bool     `json:"is_liked"`
	Status        int      `json:"status"`
	StatusText    string   `json:"status_text"`
	RejectReason  string   `json:"reject_reason,optional"`
	IsMine        bool     `json:"is_mine"`
	CreatedAt     string   `json:"created_at"`
}

type StartMatchReq struct {
	GameType       int    `json:"game_type"`                // 1=斯诺克 2=九球追分 3=中式八球 4=美式九球
	GameMode       string `json:"game_mode,optional"`       // 比赛模式
	OpponentId     int64  `json:"opponent_id"`              // 对手ID（平台用户，必填）
	OpponentName   string `json:"opponent_name"`            // 对手昵称
	OpponentAvatar string `json:"opponent_avatar,optional"` // 对手头像
}

type StartMatchResp struct {
	Success      bool              `json:"success"`
	Action       string            `json:"action,optional"`       // created/resume_existing/blocked
	BlockReason  string            `json:"block_reason,optional"` // self_ongoing/opponent_ongoing
	Message      string            `json:"message,optional"`
	MatchId      int64             `json:"match_id"`
	OngoingMatch *CurrentMatchInfo `json:"ongoing_match,optional"`
}

type StartNextRoundReq struct {
	MatchId        int64  `json:"match_id"`
	ClientActionId string `json:"client_action_id"`
	BaseRevision   int64  `json:"base_revision"`
}

type StartNextRoundResp struct {
	Accepted                  bool              `json:"accepted"`
	Success                   bool              `json:"success"`
	ClientActionId            string            `json:"client_action_id,optional"`
	ServerRevision            int64             `json:"server_revision"`
	Snapshot                  MatchSyncSnapshot `json:"snapshot"`
	RoundNo                   int               `json:"round_no"` // 新局数
	CurrentFrameStarted       bool              `json:"current_frame_started,optional"`
	CurrentFrameMyScore       int               `json:"current_frame_my_score,optional"`
	CurrentFrameOpponentScore int               `json:"current_frame_opponent_score,optional"`
	MyScore                   int               `json:"my_score"`       // 我方总分
	OpponentScore             int               `json:"opponent_score"` // 对手总分
}

type TitleInfo struct {
	Id        int64  `json:"id"`
	TitleName string `json:"title_name"`
	Source    string `json:"source"`
	Equipped  bool   `json:"equipped"`
	CreatedAt string `json:"created_at"`
}

type TournamentBracketMatch struct {
	Id              int64  `json:"id"`
	RoundNumber     int    `json:"round_number"`
	MatchOrder      int    `json:"match_order"`
	Player1Id       int64  `json:"player1_id"`
	Player1Name     string `json:"player1_name"`
	Player2Id       int64  `json:"player2_id"`
	Player2Name     string `json:"player2_name"`
	WinnerId        int64  `json:"winner_id"`
	BracketPosition string `json:"bracket_position"`
	Status          int    `json:"status"`
}

type TournamentIdReq struct {
	TournamentId int64 `json:"tournament_id"`
}

type TournamentInfo struct {
	Id             int64  `json:"id"`
	CreatorId      int64  `json:"creator_id"`
	CreatorName    string `json:"creator_name"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	CoverImage     string `json:"cover_image"`
	GameType       int    `json:"game_type"`
	Format         int    `json:"format"`
	MaxPlayers     int    `json:"max_players"`
	CurrentPlayers int    `json:"current_players"`
	Status         int    `json:"status"`
	Country        string `json:"country"`
	City           string `json:"city"`
	VenueName      string `json:"venue_name"`
	StartDate      string `json:"start_date"`
	EndDate        string `json:"end_date"`
	StartTime      string `json:"start_time,optional"`
	EndTime        string `json:"end_time,optional"`
	CreatedAt      string `json:"created_at"`
}

type TournamentParticipant struct {
	UserId    int64  `json:"user_id"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Seed      int    `json:"seed"`
	Status    int    `json:"status"`
	FinalRank int    `json:"final_rank"`
}

type TournamentShareData struct {
	TournamentId   int64  `json:"tournament_id"`
	TournamentName string `json:"tournament_name"`
	FinalRank      int    `json:"final_rank"`
	TotalPlayers   int    `json:"total_players"`
	MatchesPlayed  int    `json:"matches_played"`
	MatchesWon     int    `json:"matches_won"`
}

type TrendPoint struct {
	MatchId   int64   `json:"match_id"`
	Date      string  `json:"date"`
	WinRate   float64 `json:"win_rate"`
	RankScore int     `json:"rank_score,omitempty"`
	Result    int     `json:"result"`
}

type UpdateNicknameReq struct {
	Nickname string `json:"nickname"`
}

type UpdateNicknameResp struct {
	Success  bool      `json:"success"`
	Message  string    `json:"message"`
	UserInfo *UserInfo `json:"user_info"`
}

type UpdatePushTokenReq struct {
	PushClientId string `json:"push_client_id"`
}

type UpdateTournamentMatchReq struct {
	TournamentMatchId int64 `json:"tournament_match_id"`
	WinnerId          int64 `json:"winner_id"`
	MatchId           int64 `json:"match_id,optional"`
}

type UpdateUserPrivacyReq struct {
	HideMatchRecord bool `json:"hide_match_record"`
}

type UpdateUserPrivacyResp struct {
	Success         bool   `json:"success"`
	Message         string `json:"message"`
	HideMatchRecord bool   `json:"hide_match_record"`
}

type UpdateUserProfileReq struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UpdateUserProfileResp struct {
	Success  bool      `json:"success"`
	Message  string    `json:"message"`
	UserInfo *UserInfo `json:"user_info"`
}

type UserInfo struct {
	Id        int64  `json:"id"`
	Phone     string `json:"phone"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Status    int    `json:"status"`
	CreatedAt string `json:"created_at"`
}

type UserReputationLogItem struct {
	Id             int64  `json:"id"`
	MatchId        int64  `json:"match_id,optional"`
	ChangeType     string `json:"change_type"`
	ChangeTypeText string `json:"change_type_text"`
	ReasonCode     string `json:"reason_code"`
	ReasonText     string `json:"reason_text"`
	ChangeScore    int    `json:"change_score"`
	BeforeScore    int    `json:"before_score"`
	AfterScore     int    `json:"after_score"`
	CreatedAt      string `json:"created_at"`
}

type UserReputationLogsReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=20"`
}

type UserReputationLogsResp struct {
	Success bool                    `json:"success"`
	Total   int64                   `json:"total"`
	List    []UserReputationLogItem `json:"list"`
}

type UserStatsResp struct {
	Success      bool    `json:"success"`
	TotalMatches int     `json:"total_matches"`  // 总对局数
	Wins         int     `json:"wins"`           // 胜场数
	Losses       int     `json:"losses"`         // 负场数
	WinRate      float64 `json:"win_rate"`       // 胜率(百分比)
	MaxWinStreak int     `json:"max_win_streak"` // 最高连胜
}

type VenueAreaOption struct {
	AreaId   int64  `json:"area_id"`
	ParentId int64  `json:"parent_id"`
	Name     string `json:"name"`
}

type VenueCheckinInfo struct {
	Id        int64  `json:"id"`
	VenueId   int64  `json:"venue_id"`
	VenueName string `json:"venue_name"`
	CreatedAt string `json:"created_at"`
}

type VenueIdReq struct {
	VenueId int64 `json:"venue_id"`
}

type VenueInfo struct {
	Id            int64    `json:"id"`
	Name          string   `json:"name"`
	Address       string   `json:"address"`
	City          string   `json:"city"`
	District      string   `json:"district"`
	Latitude      float64  `json:"latitude"`
	Longitude     float64  `json:"longitude"`
	Phone         string   `json:"phone"`
	Images        []string `json:"images"`
	BusinessHours string   `json:"business_hours"`
	TableCount    int      `json:"table_count"`
	PriceRange    string   `json:"price_range"`
	Description   string   `json:"description"`
	Distance      float64  `json:"distance,omitempty"`
	CheckinCount  int      `json:"checkin_count"`
	Status        int      `json:"status"`
}

type WechatAppPayParams struct {
	Appid     string `json:"appid"`
	Partnerid string `json:"partnerid"`
	Prepayid  string `json:"prepayid"`
	Package   string `json:"package"`
	Noncestr  string `json:"noncestr"`
	Timestamp string `json:"timestamp"`
	Sign      string `json:"sign"`
}
