package model

func GetDefaultRulesContent() []RulesContent {
	return []RulesContent{
		{Category: "snooker", ContentType: "rule", Title: "开球规则", Content: "首杆需从开球区内击打红球堆，至少有一颗红球碰库或入袋。", SortOrder: 1},
		{Category: "snooker", ContentType: "rule", Title: "击球顺序", Content: "每次合法击球需遵循红球和彩球交替的基本顺序。", SortOrder: 2},
		{Category: "snooker", ContentType: "rule", Title: "得分规则", Content: "红球1分，黄2分、绿3分、咖啡4分、蓝5分、粉6分、黑7分。", SortOrder: 3},
		{Category: "snooker", ContentType: "rule", Title: "斯诺克规则", Content: "当目标球被阻挡无法直接击打时形成斯诺克，对手需尝试解球。", SortOrder: 4},
		{Category: "snooker", ContentType: "rule", Title: "复位规则", Content: "彩球在非清彩阶段入袋后需按规则点位复位。", SortOrder: 5},
		{Category: "snooker", ContentType: "foul", Title: "未击中目标球", Content: "击球后母球未先碰到当前应击打的目标球，判犯规。", SortOrder: 1},
		{Category: "snooker", ContentType: "foul", Title: "同时击中两球", Content: "母球首碰出现两颗目标球或非法连击，判犯规。", SortOrder: 2},
		{Category: "snooker", ContentType: "foul", Title: "击球入袋后白球落袋", Content: "进攻得分同时母球落袋，进球无效并判犯规。", SortOrder: 3},
		{Category: "snooker", ContentType: "glossary", Title: "斯诺克", Content: "通过障碍球让对手无法直接击中目标球的防守局面。", SortOrder: 1},
		{Category: "snooker", ContentType: "glossary", Title: "清台", Content: "从某一阶段起连续得分直至台面目标球全部清空。", SortOrder: 2},
		{Category: "snooker", ContentType: "glossary", Title: "满分147", Content: "标准规则下单杆可达到的最高分数。", SortOrder: 3},
		{Category: "snooker", ContentType: "glossary", Title: "世锦赛", Content: "斯诺克最具代表性的世界级职业赛事。", SortOrder: 4},
		{Category: "snooker", ContentType: "glossary", Title: "安全球", Content: "以限制对手进攻机会为目标的防守击球。", SortOrder: 5},
		{Category: "snooker", ContentType: "glossary", Title: "红球", Content: "每颗1分，共15颗，通常先于彩球被击打。", SortOrder: 6},
		{Category: "snooker", ContentType: "glossary", Title: "彩球", Content: "黄绿咖啡蓝粉黑，分值2到7分不等。", SortOrder: 7},
		{Category: "snooker", ContentType: "glossary", Title: "自由球", Content: "对手犯规后形成斯诺克时可指定任意球代替目标球。", SortOrder: 8},
		{Category: "snooker", ContentType: "glossary", Title: "复位", Content: "彩球入袋后按规则放回既定点位。", SortOrder: 9},
		{Category: "snooker", ContentType: "glossary", Title: "延伸", Content: "使用延长器或架杆辅助完成远距离击球。", SortOrder: 10},

		{Category: "nine_ball", ContentType: "rule", Title: "开球规则", Content: "开球需先碰1号球，并满足合法开球碰库要求。", SortOrder: 1},
		{Category: "nine_ball", ContentType: "rule", Title: "轮流击球", Content: "双方轮流上手，合法进球可继续击打。", SortOrder: 2},
		{Category: "nine_ball", ContentType: "rule", Title: "必须先碰最小号球", Content: "每杆母球首碰必须是台面最小号码目标球。", SortOrder: 3},
		{Category: "nine_ball", ContentType: "rule", Title: "9号球入袋即获胜", Content: "任何合法进攻使9号球入袋，当前局直接获胜。", SortOrder: 4},
		{Category: "nine_ball", ContentType: "rule", Title: "推球规则", Content: "开球后可选择一次推球，需提前声明且可能交由对手选择击打。", SortOrder: 5},
		{Category: "nine_ball", ContentType: "foul", Title: "未碰到最小号球", Content: "母球首碰不是当前最小号目标球，判犯规。", SortOrder: 1},
		{Category: "nine_ball", ContentType: "foul", Title: "白球落袋", Content: "母球入袋或离台，判犯规并由对手自由摆球。", SortOrder: 2},
		{Category: "nine_ball", ContentType: "foul", Title: "击球后无球碰库", Content: "击球后若无目标球入袋且无任何球碰库，判犯规。", SortOrder: 3},
		{Category: "nine_ball", ContentType: "glossary", Title: "冲球", Content: "开球阶段以力量打散球堆并争取进球机会。", SortOrder: 1},
		{Category: "nine_ball", ContentType: "glossary", Title: "黄金开球", Content: "开球时直接将9号球合法击入袋中。", SortOrder: 2},
		{Category: "nine_ball", ContentType: "glossary", Title: "推球", Content: "开球后允许的一次特殊击球，不受先碰目标球限制。", SortOrder: 3},
		{Category: "nine_ball", ContentType: "glossary", Title: "跳球", Content: "通过击打让母球跃起越过障碍球。", SortOrder: 4},
		{Category: "nine_ball", ContentType: "glossary", Title: "安全球", Content: "以防守为目标，让对手进入不利局面。", SortOrder: 5},
		{Category: "nine_ball", ContentType: "glossary", Title: "斯登", Content: "击球后母球强制刹停，减少走位距离。", SortOrder: 6},
		{Category: "nine_ball", ContentType: "glossary", Title: "防守", Content: "通过走位和障碍制造对手失误机会。", SortOrder: 7},
		{Category: "nine_ball", ContentType: "glossary", Title: "走位", Content: "控制母球落点，为下一杆创造有利角度。", SortOrder: 8},
		{Category: "nine_ball", ContentType: "glossary", Title: "做球", Content: "提前布局下一颗目标球的进攻线路。", SortOrder: 9},
		{Category: "nine_ball", ContentType: "glossary", Title: "翻袋", Content: "利用库边反弹线路将目标球击入袋口。", SortOrder: 10},

		{Category: "chinese_eight", ContentType: "rule", Title: "开球规则", Content: "开球需满足合法碰库或入袋条件，未满足则可重开或继续。", SortOrder: 1},
		{Category: "chinese_eight", ContentType: "rule", Title: "选色规则", Content: "首个合法入袋球决定击球方为全色球或花色球。", SortOrder: 2},
		{Category: "chinese_eight", ContentType: "rule", Title: "8号球击入规则", Content: "清完本方目标球后方可按指球指袋击打8号球。", SortOrder: 3},
		{Category: "chinese_eight", ContentType: "rule", Title: "连续击球规则", Content: "合法进球且未犯规可持续上手，直到未进球或犯规。", SortOrder: 4},
		{Category: "chinese_eight", ContentType: "rule", Title: "犯规处理", Content: "常见犯规后对手通常获得自由球或手中球优势。", SortOrder: 5},
		{Category: "chinese_eight", ContentType: "foul", Title: "白球落袋", Content: "母球入袋判犯规，交换击球权并给对手手中球。", SortOrder: 1},
		{Category: "chinese_eight", ContentType: "foul", Title: "先碰对方球", Content: "母球首碰对方花色球或8号球，判犯规。", SortOrder: 2},
		{Category: "chinese_eight", ContentType: "foul", Title: "击球后无球碰库", Content: "无进球且无任一球碰库，判犯规。", SortOrder: 3},
		{Category: "chinese_eight", ContentType: "glossary", Title: "全色球", Content: "编号1到7的实心球。", SortOrder: 1},
		{Category: "chinese_eight", ContentType: "glossary", Title: "花色球", Content: "编号9到15的条纹球。", SortOrder: 2},
		{Category: "chinese_eight", ContentType: "glossary", Title: "8号球", Content: "黑8，决定胜负的关键目标球。", SortOrder: 3},
		{Category: "chinese_eight", ContentType: "glossary", Title: "开球权", Content: "本局首杆击球资格，通常由抽签或前局结果决定。", SortOrder: 4},
		{Category: "chinese_eight", ContentType: "glossary", Title: "指球指袋", Content: "声明目标球与入袋口后才视为有效进球。", SortOrder: 5},
		{Category: "chinese_eight", ContentType: "glossary", Title: "炸清", Content: "开球方从上手后连续清台直至获胜。", SortOrder: 6},
		{Category: "chinese_eight", ContentType: "glossary", Title: "接清", Content: "后手上场后一次性清台并直接取胜。", SortOrder: 7},
		{Category: "chinese_eight", ContentType: "glossary", Title: "走位", Content: "通过控制母球停位衔接后续进攻。", SortOrder: 8},
		{Category: "chinese_eight", ContentType: "glossary", Title: "翻袋", Content: "借助库边反弹将目标球打入指定袋口。", SortOrder: 9},
		{Category: "chinese_eight", ContentType: "glossary", Title: "跳球", Content: "使母球腾空越过障碍后完成合法击球。", SortOrder: 10},
	}
}
