// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"billiard_master/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 手机号登录/注册
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				// OAuth登录
				Method:  http.MethodPost,
				Path:    "/login-by-oauth",
				Handler: LoginByOauthHandler(serverCtx),
			},
			{
				// 发送短信验证码
				Method:  http.MethodPost,
				Path:    "/send-sms",
				Handler: SendSmsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取公开对局详情
				Method:  http.MethodGet,
				Path:    "/match/detail",
				Handler: GetPublicMatchDetailHandler(serverCtx),
			},
			{
				// 获取正在进行的对局列表
				Method:  http.MethodGet,
				Path:    "/matches/ongoing",
				Handler: GetOngoingMatchesHandler(serverCtx),
			},
			{
				// 获取段位排行榜
				Method:  http.MethodGet,
				Path:    "/rank/leaderboard",
				Handler: GetLeaderboardHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/public"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 绑定手机号
				Method:  http.MethodPost,
				Path:    "/bind-phone",
				Handler: BindPhoneHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取当前用户信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: GetUserInfoHandler(serverCtx),
			},
			{
				// 更新昵称
				Method:  http.MethodPost,
				Path:    "/nickname",
				Handler: UpdateNicknameHandler(serverCtx),
			},
			{
				// 更新推送令牌
				Method:  http.MethodPost,
				Path:    "/push-token",
				Handler: UpdatePushTokenHandler(serverCtx),
			},
			{
				// 获取用户统计数据
				Method:  http.MethodGet,
				Path:    "/stats",
				Handler: GetUserStatsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 取消对局
				Method:  http.MethodPost,
				Path:    "/cancel",
				Handler: CancelMatchHandler(serverCtx),
			},
			{
				// 获取进行中对局
				Method:  http.MethodGet,
				Path:    "/current",
				Handler: GetCurrentMatchHandler(serverCtx),
			},
			{
				// 获取对局详情
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: GetMatchDetailHandler(serverCtx),
			},
			{
				// 结束对局
				Method:  http.MethodPost,
				Path:    "/finish",
				Handler: FinishMatchHandler(serverCtx),
			},
			{
				// 犯规
				Method:  http.MethodPost,
				Path:    "/foul",
				Handler: MatchFoulHandler(serverCtx),
			},
			{
				// 获取交锋历史
				Method:  http.MethodGet,
				Path:    "/h2h/history",
				Handler: GetH2HHistoryHandler(serverCtx),
			},
			{
				// 获取交锋统计
				Method:  http.MethodGet,
				Path:    "/h2h/stats",
				Handler: GetH2HStatsHandler(serverCtx),
			},
			{
				// 获取对局列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: GetMatchListHandler(serverCtx),
			},
			{
				// 获取匹配二维码
				Method:  http.MethodGet,
				Path:    "/qrcode",
				Handler: GetMatchQRCodeHandler(serverCtx),
			},
			{
				// 结束一局
				Method:  http.MethodPost,
				Path:    "/round/end",
				Handler: EndRoundHandler(serverCtx),
			},
			{
				// 开始下一局
				Method:  http.MethodPost,
				Path:    "/round/start",
				Handler: StartNextRoundHandler(serverCtx),
			},
			{
				// 加分
				Method:  http.MethodPost,
				Path:    "/score",
				Handler: MatchScoreHandler(serverCtx),
			},
			{
				// 开始对局
				Method:  http.MethodPost,
				Path:    "/start",
				Handler: StartMatchHandler(serverCtx),
			},
			{
				// 撤销操作
				Method:  http.MethodPost,
				Path:    "/undo",
				Handler: MatchUndoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/match"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取对手列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: GetOpponentListHandler(serverCtx),
			},
			{
				// 搜索对手
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: SearchOpponentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/opponent"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户段位信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: GetUserRankInfoHandler(serverCtx),
			},
			{
				// 获取段位列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: GetRankListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/rank"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取成就列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: GetAchievementListHandler(serverCtx),
			},
			{
				// 装备/卸下称号
				Method:  http.MethodPost,
				Path:    "/title/equip",
				Handler: EquipTitleHandler(serverCtx),
			},
			{
				// 获取用户称号列表
				Method:  http.MethodGet,
				Path:    "/titles",
				Handler: GetUserTitlesHandler(serverCtx),
			},
			{
				// 获取已解锁成就
				Method:  http.MethodGet,
				Path:    "/unlocked",
				Handler: GetUserAchievementsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/achievement"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 接受好友请求
				Method:  http.MethodPost,
				Path:    "/accept",
				Handler: AcceptFriendRequestHandler(serverCtx),
			},
			{
				// 删除好友
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: DeleteFriendHandler(serverCtx),
			},
			{
				// 获取好友列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: GetFriendListHandler(serverCtx),
			},
			{
				// 拒绝好友请求
				Method:  http.MethodPost,
				Path:    "/reject",
				Handler: RejectFriendRequestHandler(serverCtx),
			},
			{
				// 发送好友请求
				Method:  http.MethodPost,
				Path:    "/request",
				Handler: SendFriendRequestHandler(serverCtx),
			},
			{
				// 获取好友请求列表
				Method:  http.MethodGet,
				Path:    "/requests",
				Handler: GetFriendRequestsHandler(serverCtx),
			},
			{
				// 搜索用户
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: SearchFriendUserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/friend"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 关注用户
				Method:  http.MethodPost,
				Path:    "/follow",
				Handler: FollowUserHandler(serverCtx),
			},
			{
				// 获取粉丝列表
				Method:  http.MethodGet,
				Path:    "/followers",
				Handler: GetFollowerListHandler(serverCtx),
			},
			{
				// 获取关注列表
				Method:  http.MethodGet,
				Path:    "/following",
				Handler: GetFollowingListHandler(serverCtx),
			},
			{
				// 取消关注
				Method:  http.MethodPost,
				Path:    "/unfollow",
				Handler: UnfollowUserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/follow"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取广场动态
				Method:  http.MethodGet,
				Path:    "/public",
				Handler: GetPublicPostsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/social"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 评论动态
				Method:  http.MethodPost,
				Path:    "/comment",
				Handler: CommentPostHandler(serverCtx),
			},
			{
				// 获取动态评论
				Method:  http.MethodGet,
				Path:    "/comments",
				Handler: GetPostCommentsHandler(serverCtx),
			},
			{
				// 删除动态
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: DeletePostHandler(serverCtx),
			},
			{
				// 获取关注的人的动态
				Method:  http.MethodGet,
				Path:    "/feed",
				Handler: GetPostListHandler(serverCtx),
			},
			{
				// 点赞动态
				Method:  http.MethodPost,
				Path:    "/like",
				Handler: LikePostHandler(serverCtx),
			},
			{
				// 发布动态
				Method:  http.MethodPost,
				Path:    "/post",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				// 取消点赞
				Method:  http.MethodPost,
				Path:    "/unlike",
				Handler: UnlikePostHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/social"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 接受挑战
				Method:  http.MethodPost,
				Path:    "/accept",
				Handler: AcceptChallengeHandler(serverCtx),
			},
			{
				// 获取待处理挑战
				Method:  http.MethodGet,
				Path:    "/pending",
				Handler: GetPendingChallengesHandler(serverCtx),
			},
			{
				// 拒绝挑战
				Method:  http.MethodPost,
				Path:    "/reject",
				Handler: RejectChallengeHandler(serverCtx),
			},
			{
				// 发起挑战
				Method:  http.MethodPost,
				Path:    "/send",
				Handler: SendChallengeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/challenge"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取赛事对阵图
				Method:  http.MethodGet,
				Path:    "/bracket",
				Handler: GetTournamentBracketHandler(serverCtx),
			},
			{
				// 获取赛事详情
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: GetTournamentDetailHandler(serverCtx),
			},
			{
				// 获取赛事列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: GetTournamentListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/tournament"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 取消赛事
				Method:  http.MethodPost,
				Path:    "/cancel",
				Handler: CancelTournamentHandler(serverCtx),
			},
			{
				// 签到赛事
				Method:  http.MethodPost,
				Path:    "/checkin",
				Handler: CheckinTournamentHandler(serverCtx),
			},
			{
				// 创建赛事
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: CreateTournamentHandler(serverCtx),
			},
			{
				// 结束赛事
				Method:  http.MethodPost,
				Path:    "/finish",
				Handler: FinishTournamentHandler(serverCtx),
			},
			{
				// 报名赛事
				Method:  http.MethodPost,
				Path:    "/join",
				Handler: JoinTournamentHandler(serverCtx),
			},
			{
				// 退出赛事
				Method:  http.MethodPost,
				Path:    "/leave",
				Handler: LeaveTournamentHandler(serverCtx),
			},
			{
				// 更新赛事对局结果
				Method:  http.MethodPost,
				Path:    "/match/update",
				Handler: UpdateTournamentMatchHandler(serverCtx),
			},
			{
				// 获取我的赛事
				Method:  http.MethodGet,
				Path:    "/my",
				Handler: GetMyTournamentsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/tournament"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取当前赛季
				Method:  http.MethodGet,
				Path:    "/current",
				Handler: GetCurrentSeasonHandler(serverCtx),
			},
			{
				// 获取赛季排行榜
				Method:  http.MethodGet,
				Path:    "/leaderboard",
				Handler: GetSeasonLeaderboardHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/season"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取我的赛季记录
				Method:  http.MethodGet,
				Path:    "/my-record",
				Handler: GetMySeasonRecordHandler(serverCtx),
			},
			{
				// 获取赛季报告
				Method:  http.MethodGet,
				Path:    "/report",
				Handler: GetSeasonReportHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/season"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取球馆详情
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: GetVenueDetailHandler(serverCtx),
			},
			{
				// 获取球馆列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: GetVenueListHandler(serverCtx),
			},
			{
				// 获取附近球馆
				Method:  http.MethodGet,
				Path:    "/nearby",
				Handler: GetNearbyVenuesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/venue"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 打卡球馆
				Method:  http.MethodPost,
				Path:    "/checkin",
				Handler: CheckinVenueHandler(serverCtx),
			},
			{
				// 创建球馆
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: CreateVenueHandler(serverCtx),
			},
			{
				// 获取我的打卡记录
				Method:  http.MethodGet,
				Path:    "/my-checkins",
				Handler: GetMyCheckinsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/venue"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取规则分类
				Method:  http.MethodGet,
				Path:    "/categories",
				Handler: GetRuleCategoriesHandler(serverCtx),
			},
			{
				// 获取规则内容
				Method:  http.MethodGet,
				Path:    "/content",
				Handler: GetRuleContentHandler(serverCtx),
			},
			{
				// 获取术语词典
				Method:  http.MethodGet,
				Path:    "/glossary",
				Handler: GetGlossaryHandler(serverCtx),
			},
			{
				// 搜索规则
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: SearchRulesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/rules"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 删除通知
				Method:  http.MethodPost,
				Path:    "/delete",
				Handler: DeleteNotificationHandler(serverCtx),
			},
			{
				// 获取通知列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: GetNotificationListHandler(serverCtx),
			},
			{
				// 标记已读
				Method:  http.MethodPost,
				Path:    "/read",
				Handler: MarkNotificationReadHandler(serverCtx),
			},
			{
				// 全部标记已读
				Method:  http.MethodPost,
				Path:    "/read-all",
				Handler: MarkAllNotificationsReadHandler(serverCtx),
			},
			{
				// 获取未读数量
				Method:  http.MethodGet,
				Path:    "/unread-count",
				Handler: GetUnreadCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/notification"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取对局分享数据
				Method:  http.MethodGet,
				Path:    "/match",
				Handler: GetMatchShareDataHandler(serverCtx),
			},
			{
				// 获取赛事分享数据
				Method:  http.MethodGet,
				Path:    "/tournament",
				Handler: GetTournamentShareDataHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/share"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 分球种统计
				Method:  http.MethodGet,
				Path:    "/by-game-type",
				Handler: GetStatsByGameTypeHandler(serverCtx),
			},
			{
				// 对局时长统计
				Method:  http.MethodGet,
				Path:    "/match-duration",
				Handler: GetMatchDurationStatsHandler(serverCtx),
			},
			{
				// 强弱对手分析
				Method:  http.MethodGet,
				Path:    "/opponent-strength",
				Handler: GetOpponentStrengthHandler(serverCtx),
			},
			{
				// 段位分变化趋势
				Method:  http.MethodGet,
				Path:    "/rank-score-trend",
				Handler: GetRankScoreTrendHandler(serverCtx),
			},
			{
				// 近N场胜率趋势
				Method:  http.MethodGet,
				Path:    "/recent-trend",
				Handler: GetRecentTrendHandler(serverCtx),
			},
			{
				// 单杆最高分记录
				Method:  http.MethodGet,
				Path:    "/single-high-score",
				Handler: GetSingleHighScoreHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/stats"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 检查管理员账号是否存在
				Method:  http.MethodGet,
				Path:    "/exists",
				Handler: AdminExistsHandler(serverCtx),
			},
			{
				// 初始化管理员账号
				Method:  http.MethodPost,
				Path:    "/init",
				Handler: AdminInitHandler(serverCtx),
			},
			{
				// 管理员登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: AdminLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 修改管理员密码
				Method:  http.MethodPost,
				Path:    "/change-password",
				Handler: AdminChangePasswordHandler(serverCtx),
			},
			{
				// 获取当前管理员信息
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: AdminUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取球馆列表（管理员）
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: AdminGetVenueListHandler(serverCtx),
			},
			{
				// 审核球馆
				Method:  http.MethodPost,
				Path:    "/review",
				Handler: AdminReviewVenueHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin/venue"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户列表（管理员）
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: AdminGetUserListHandler(serverCtx),
			},
			{
				// 更新用户状态
				Method:  http.MethodPost,
				Path:    "/update-status",
				Handler: AdminUpdateUserStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin/users"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取最近对局
				Method:  http.MethodGet,
				Path:    "/recent-matches",
				Handler: AdminGetRecentMatchesHandler(serverCtx),
			},
			{
				// 获取最近注册用户
				Method:  http.MethodGet,
				Path:    "/recent-users",
				Handler: AdminGetRecentUsersHandler(serverCtx),
			},
			{
				// 获取首页统计数据
				Method:  http.MethodGet,
				Path:    "/stats",
				Handler: AdminGetDashboardStatsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin/dashboard"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取对局列表（管理员）
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: AdminGetMatchListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/admin/match"),
	)
}
